import { useRef, useState } from "react";
import { useQuery } from "../hooks/useQuery";
import { STATIC, api, type AskResult, type AskTurn } from "../lib/api";

interface Exchange {
  question: string;
  result?: AskResult;
  error?: string;
  pending?: boolean;
}

function ResultTable({ r }: { r: AskResult }) {
  if (!r.columns.length) return null;
  return (
    <div className="mt-3 overflow-auto rounded border border-gray-200 bg-white">
      <table className="w-full text-sm">
        <thead>
          <tr className="bg-slate-700 text-left text-white">
            {r.columns.map((c) => (
              <th key={c} className="whitespace-nowrap px-3 py-1.5 font-semibold">{c}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {r.rows.map((row, i) => (
            <tr key={i} className={i % 2 ? "bg-slate-50" : ""}>
              {row.map((v, j) => (
                <td key={j} className="whitespace-nowrap px-3 py-1.5 text-slate-700">
                  {v === null || v === undefined
                    ? <span className="text-slate-400">—</span>
                    : typeof v === "number" ? v.toLocaleString() : String(v)}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default function Ask() {
  const status = useQuery(() => api.askStatus(), []);
  const examples = useQuery(() => api.askExamples(), []);
  const [q, setQ] = useState("");
  const views = useQuery(() => api.askViews(), []);
  const [view, setView] = useState("catalog");
  const [log, setLog] = useState<Exchange[]>([]);
  const [busy, setBusy] = useState(false);
  const [showSql, setShowSql] = useState<Record<number, boolean>>({});
  const endRef = useRef<HTMLDivElement>(null);

  async function run(question: string) {
    const text = question.trim();
    if (!text || busy) return;
    setQ("");
    setBusy(true);
    const idx = log.length;
    setLog((l) => [...l, { question: text, pending: true }]);

    // send prior turns so follow-ups ("break that down by line of business")
    // resolve against the earlier question rather than starting cold
    const history: AskTurn[] = [];
    for (const e of log) {
      history.push({ role: "user", text: e.question });
      if (e.result?.answer) history.push({ role: "analyst", text: e.result.answer });
    }
    history.push({ role: "user", text });

    try {
      const result = await api.ask(history, view);
      setLog((l) => l.map((e, i) => (i === idx ? { question: text, result } : e)));
    } catch (err: any) {
      setLog((l) =>
        l.map((e, i) => (i === idx ? { question: text, error: String(err.message || err) } : e)));
    } finally {
      setBusy(false);
      requestAnimationFrame(() => endRef.current?.scrollIntoView({ behavior: "smooth" }));
    }
  }

  if (STATIC) {
    return (
      <div className="rounded-lg border border-gray-200 bg-white p-6">
        <div className="text-sm font-semibold text-slate-800">
          Ask the Ontology is not available in the public build
        </div>
        <p className="mt-2 max-w-2xl text-sm leading-relaxed text-slate-600">
          Answers are generated by Cortex Analyst against a semantic view in Snowflake,
          which needs credentials. This snapshot is published without any, so the page is
          disabled rather than shown broken. Run the app locally against your own account
          to use it — every other page works here from baked data.
        </p>
      </div>
    );
  }

  if (status.data && !status.data.ok) {
    return (
      <div className="rounded border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900">
        <p className="font-semibold">Cortex Analyst is not configured.</p>
        <p className="mt-1">
          Missing environment variables: {status.data.missing.join(", ")}. Set them in{" "}
          <code className="rounded bg-amber-100 px-1">server/.env</code> and restart the server.
        </p>
      </div>
    );
  }

  return (
    <div className="mx-auto flex max-w-4xl flex-col gap-4">
      <div className="rounded border border-gray-200 bg-white p-4">
        <p className="text-sm text-slate-600">
          Ask questions about the SAP BDC ontology in plain language. Cortex Analyst
          translates them to SQL against the semantic view and the results are shown below.
        </p>
        <div className="mt-3 flex flex-wrap gap-2">
          {(views.data ?? []).map((v) => (
            <button key={v.key} onClick={() => { setView(v.key); setLog([]); }}
              className={`rounded-full border px-3 py-1 text-xs ${view === v.key ? "border-sky-500 bg-sky-500 text-white" : "border-slate-300 bg-white text-slate-600 hover:bg-slate-50"}`}>
              {v.label}</button>
          ))}
        </div>
        <p className="mt-1 font-mono text-xs text-slate-400">
          {(views.data ?? []).find((v) => v.key === view)?.name ?? status.data?.semantic_view}</p>
      </div>

      {!log.length && examples.data && (
        <div className="rounded border border-gray-200 bg-white p-4">
          <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-500">
            Try one of these
          </p>
          <div className="flex flex-wrap gap-2">
            {examples.data.map((e) => (
              <button key={e} onClick={() => run(e)} disabled={busy}
                className="rounded-full border border-sky-200 bg-sky-50 px-3 py-1 text-xs text-sky-800 hover:bg-sky-100 disabled:opacity-50">
                {e}
              </button>
            ))}
          </div>
        </div>
      )}

      {log.map((e, i) => (
        <div key={i} className="rounded border border-gray-200 bg-white p-4">
          <p className="font-semibold text-slate-800">{e.question}</p>

          {e.pending && (
            <p className="mt-2 animate-pulse text-sm text-sky-600">
              Asking Cortex Analyst…
            </p>
          )}

          {e.error && (
            <div className="mt-2 rounded border border-rose-200 bg-rose-50 p-2 text-sm text-rose-800">
              {e.error}
            </div>
          )}

          {e.result && (
            <>
              {e.result.answer && (
                <p className="mt-2 whitespace-pre-wrap text-sm text-slate-600">
                  {e.result.answer}
                </p>
              )}
              <ResultTable r={e.result} />
              <div className="mt-2 flex items-center gap-3 text-xs text-slate-500">
                {e.result.rowCount > 0 && (
                  <span>
                    {e.result.rowCount.toLocaleString()} row
                    {e.result.rowCount === 1 ? "" : "s"}
                    {e.result.truncated && " (truncated at 500)"}
                  </span>
                )}
                {e.result.sql && (
                  <button onClick={() => setShowSql((s) => ({ ...s, [i]: !s[i] }))}
                    className="text-sky-600 hover:underline">
                    {showSql[i] ? "hide SQL" : "show SQL"}
                  </button>
                )}
              </div>
              {showSql[i] && e.result.sql && (
                <pre className="mt-2 overflow-auto rounded bg-slate-900 p-3 text-xs leading-relaxed text-slate-100">
                  {e.result.sql}
                </pre>
              )}
              {!!e.result.suggestions.length && (
                <div className="mt-3 flex flex-wrap gap-2">
                  {e.result.suggestions.map((s) => (
                    <button key={s} onClick={() => run(s)} disabled={busy}
                      className="rounded-full border border-slate-200 bg-slate-50 px-3 py-1 text-xs text-slate-700 hover:bg-slate-100 disabled:opacity-50">
                      {s}
                    </button>
                  ))}
                </div>
              )}
            </>
          )}
        </div>
      ))}

      <div ref={endRef} />

      <form onSubmit={(ev) => { ev.preventDefault(); run(q); }}
        className="sticky bottom-0 flex gap-2 bg-slate-50 pb-2 pt-1">
        <input value={q} onChange={(ev) => setQ(ev.target.value)}
          placeholder="Ask about products, entities, processes or coverage…"
          className="flex-1 rounded border border-gray-300 px-3 py-2 text-sm outline-none focus:border-sky-400" />
        <button type="submit" disabled={busy || !q.trim()}
          className="rounded bg-sky-600 px-4 py-2 text-sm font-semibold text-white hover:bg-sky-700 disabled:opacity-40">
          {busy ? "Asking…" : "Ask"}
        </button>
        {!!log.length && (
          <button type="button" onClick={() => setLog([])} disabled={busy}
            className="rounded border border-gray-300 px-3 py-2 text-sm text-slate-600 hover:bg-white disabled:opacity-40">
            Clear
          </button>
        )}
      </form>
    </div>
  );
}
